### PR TITLE
Generators should be aware of reserved names

### LINKED ISSUE #921: generator unaware of reserved names
In a new phoenix project: 
```bash
$ mix phoenix.new throwaway 
#install all dependencies
$ cd throwaway    
$ mix phoenix.gen.html Repo repos
# add resources "/repos", RepoController to web/router.ex
$ mix ecto.migrate
=INFO REPORT==== 29-May-2015::10:40:22 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application throwaway: Throwaway.start(:normal, []) returned an error: shutdown: failed to start child: Throwaway.Repo
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function: Throwaway.Repo.start_link/0
            (throwaway) Throwaway.Repo.start_link()
            (stdlib) supervisor.erl:314: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:297: :supervisor.start_children/3
            (stdlib) supervisor.erl:263: :supervisor.init_children/2
            (stdlib) gen_server.erl:306: :gen_server.init_it/6
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

The problem being that `Repo` is a name already in use.

### PR DESCRIPTION
**Pull request by doomspork**
RFC @josevalim — Thanks for letting me take a stab at this, looking forward to your feedback.

This closes #921.

### CODE REVIEW

File: lib/mix/phoenix.ex [hunk 1]
```diff
@@ -93,6 +93,16 @@ defmodule Mix.Phoenix do
   end
 
   @doc """
+  Checks the availability of a given module name.
+  """
+  def check_module_name_availability!(name) do
```
Comment (doomspork) [inline lib/mix/phoenix.ex]: I copied the `check_module_name_availability!` verbatim, as I saw little need to modify it.

File: lib/mix/tasks/phoenix.gen.channel.ex [hunk 2]
```diff
@@ -52,6 +52,11 @@ defmodule Mix.Tasks.Phoenix.Gen.Channel do
     unless length(args) == 2 do
       raise_with_help
     end
+
+    args
```
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.channel.ex]: The generated module contains `Channel` at the end. So I wouldn't check it here but just after we call `Mix.Project.inflect`.

File: lib/mix/tasks/phoenix.gen.html.ex [hunk 3]
```diff
@@ -66,7 +66,8 @@ defmodule Mix.Tasks.Phoenix.Gen.Html do
     end
   end
 
-  defp validate_args!([_, plural | _] = args) do
+  defp validate_args!([singular, plural | _] = args) do
+    Mix.Phoenix.check_module_name_availability!(singular)
```
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.html.ex]: Same here. The generate modules end with "Controller" and "View".

File: lib/mix/tasks/phoenix.gen.json.ex [hunk 4]
```diff
@@ -65,7 +65,8 @@ defmodule Mix.Tasks.Phoenix.Gen.Json do
     end
   end
 
-  defp validate_args!([_, plural | _] = args) do
+  defp validate_args!([singular, plural | _] = args) do
+    Mix.Phoenix.check_module_name_availability!(singular)
```
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.json.ex]: Same here. The generate modules end with "Controller" and "View".

File: lib/mix/tasks/phoenix.gen.channel.ex (hunk 2 above)
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.channel.ex]: Also, the generate module is almost always namespaced and the namespace is not considered here.

File: lib/mix/tasks/phoenix.gen.model.ex [hunk 5]
```diff
@@ -70,7 +70,8 @@ defmodule Mix.Tasks.Phoenix.Gen.Model do
     ]
   end
 
-  defp validate_args!([_, plural | _] = args) do
+  defp validate_args!([singular, plural | _] = args) do
+    Mix.Phoenix.check_module_name_availability!(singular)
```
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.model.ex]: Same here, too soon, it is not considering the namespace.

File: test/mix/tasks/phoenix.gen.channel_test.exs [hunk 6]
```diff
@@ -76,4 +76,10 @@ defmodule Mix.Tasks.Phoenix.Gen.ChannelTest do
       Mix.Tasks.Phoenix.Gen.Channel.run ["Admin.Room", "rooms", "new_message"]
     end
   end
+
+  test "name can't already be defined" do
+    assert_raise Mix.Error, fn ->
+      Mix.Tasks.Phoenix.Gen.Channel.run ["String", "strings"]
```
Comment (josevalim) [inline test/mix/tasks/phoenix.gen.channel_test.exs]: So this should work because `MyApp.StringChannel` would be generated.

**Comment by josevalim** [comment]
Thanks @doomspork!  Unfortunately we are checking at the wrong place, I think we should check the arguments after we call inflect. :) Thoughts?

**Comment by doomspork** [comment]
@josevalim thanks for the feedback!  My thinking was to exit as soon as possible for keywords but you've raise good points, I will make those changes today.

File: lib/mix/tasks/phoenix.gen.channel.ex (hunk 2 above)
Comment (doomspork) [inline lib/mix/tasks/phoenix.gen.channel.ex]: @josevalim does the namespace need to be considered?  In issue #921, even within the `Throwaway` namespace an error is still raised:

```elixir
(UndefinedFunctionError) undefined function: Throwaway.Repo.start_link/0
```

Apologizes in advance if I'm confused :smile:, thanks for your guidance.

File: lib/mix/tasks/phoenix.gen.model.ex (hunk 5 above)
Comment (doomspork) [inline lib/mix/tasks/phoenix.gen.model.ex]: @josevalim does the namespace need to be considered?  In issue #921, even within the `Throwaway` namespace an error is still raised:

```elixir
(UndefinedFunctionError) undefined function: Throwaway.Repo.start_link/0
```

Apologizes in advance if I'm confused :smile:, thanks for your guidance.

File: lib/mix/tasks/phoenix.gen.html.ex (hunk 3 above)
Comment (doomspork) [inline lib/mix/tasks/phoenix.gen.html.ex]: Sounds like this check should only occur in the Model generator where it is not appended with `View`, `Controller`, or `Channel`.  Thoughts?

File: test/mix/tasks/phoenix.gen.channel_test.exs (hunk 6 above)
Comment (doomspork) [inline test/mix/tasks/phoenix.gen.channel_test.exs]: I'll remove the checks/tests for `Channel` since it does not appear to suffer from keyword problem..

File: lib/mix/tasks/phoenix.gen.html.ex (hunk 3 above)
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.html.ex]: It doesn't work even for the model generator because we need to consider the namespace. If we don't consider the namespace, we won't even detect the case in #921 as the conflict there is effectively with a namespace module.

File: lib/mix/tasks/phoenix.gen.channel.ex [hunk 7]
```diff
@@ -25,6 +25,8 @@ defmodule Mix.Tasks.Phoenix.Gen.Channel do
 
     binding = binding ++ [plural: plural]
 
+    Mix.Phoenix.check_module_name_availability!(binding[:module])
```
Comment (doomspork) [inline lib/mix/tasks/phoenix.gen.channel.ex]: @josevalim is this what you had in mind?  Thank you very much for your feedback.

Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.channel.ex]: Almost! You need to add the suffix here:

     Mix.Phoenix.check_module_name_availability!(binding[:module] <> "Channel")

File: lib/mix/tasks/phoenix.gen.html.ex [hunk 8]
```diff
@@ -39,6 +39,8 @@ defmodule Mix.Tasks.Phoenix.Gen.Html do
     binding = binding ++ [plural: plural, route: route,
                           inputs: inputs(attrs), params: Mix.Phoenix.params(attrs)]
 
+    Mix.Phoenix.check_module_name_availability!(binding[:module])
```
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.html.ex]: This should be called twice:

     Mix.Phoenix.check_module_name_availability!(binding[:module] <> "Controller")
     Mix.Phoenix.check_module_name_availability!(binding[:module] <> "View")

File: lib/mix/tasks/phoenix.gen.json.ex [hunk 9]
```diff
@@ -37,6 +37,8 @@ defmodule Mix.Tasks.Phoenix.Gen.Json do
     route   = String.split(path, "/") |> Enum.drop(-1) |> Kernel.++([plural]) |> Enum.join("/")
     binding = binding ++ [plural: plural, route: route, params: Mix.Phoenix.params(attrs)]
 
+    Mix.Phoenix.check_module_name_availability!(binding[:module])
```
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.json.ex]: Twice too!

File: lib/mix/tasks/phoenix.gen.model.ex [hunk 10]
```diff
@@ -56,6 +56,8 @@ defmodule Mix.Tasks.Phoenix.Gen.Model do
     path      = binding[:path]
     migration = String.replace(path, "/", "_")
 
+    Mix.Phoenix.check_module_name_availability!(binding[:module])
```
Comment (josevalim) [inline lib/mix/tasks/phoenix.gen.model.ex]: This one is correct.

File: test/mix/tasks/phoenix.gen.channel_test.exs [hunk 11]
```diff
@@ -76,4 +76,10 @@ defmodule Mix.Tasks.Phoenix.Gen.ChannelTest do
       Mix.Tasks.Phoenix.Gen.Channel.run ["Admin.Room", "rooms", "new_message"]
     end
   end
+
+  test "name can't already be defined" do
+    assert_raise Mix.Error, fn ->
+      Mix.Tasks.Phoenix.Gen.Channel.run ["Channel", "channels"]
```
Comment (josevalim) [inline test/mix/tasks/phoenix.gen.channel_test.exs]: If you call it with "Channel", it is going to generate `Phoenix.ChannelChannel` so this test is passing by accident because you are checking the wrong thing. :) Once you do the changes above, this test should fail again.

File: lib/mix/tasks/phoenix.gen.model.ex (hunk 10 above)
Comment (doomspork) [inline lib/mix/tasks/phoenix.gen.model.ex]: I got one right! :tada:

File: test/mix/tasks/phoenix.gen.channel_test.exs (hunk 11 above)
Comment (doomspork) [inline test/mix/tasks/phoenix.gen.channel_test.exs]: You are correct, this test now fails with the updated changes.  Any recommendations on how best to test this?

Comment (josevalim) [inline test/mix/tasks/phoenix.gen.channel_test.exs]: You will have to define dummy modules at the top of the file. I would call them "Dup". `Phoenix.DupChannel`, `Phoenix.DupHTMLView`, `Phoenix.DupHTMLController`, etc.

Comment (doomspork) [inline test/mix/tasks/phoenix.gen.channel_test.exs]: Great, that's what I was thinking but I wasn't sure if it was kosher.  Appreciate all your feedback @josevalim, dziękuję!

**Comment by doomspork** [comment]
Thanks for all of your feedback @josevalim, I believe I have incorporated it all.

File: test/mix/tasks/phoenix.gen.model_test.exs [hunk 12]
```diff
@@ -1,5 +1,8 @@
 Code.require_file "../../../installer/test/mix_helper.exs", __DIR__
 
+defmodule Phoenix.Dup do
```
Comment (doomspork) [inline test/mix/tasks/phoenix.gen.model_test.exs]: I created a `Dup` model for consistency sake.

**Comment by doomspork** [comment]
Let me know if you have any additional feedback @josevalim, thanks again.

**Comment by josevalim** [comment]
Thank you! Can you please squash your commits together? Then this is ready to go! :heart:

**Comment by doomspork** [comment]
Squashed!  Thanks @josevalim, you da :bomb:.

**Comment by doomspork** [comment]
@josevalim any ideas why this is failing on Travis?  It passes for me with the ` 881247` seed.

**Comment by josevalim** [comment]
There are some race conditions in the test suite when we are doing integration tests, i will take a look at those later.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
