### PR TITLE
fix: check ECTO_IPV6 for falsey values to enable ipv6

### LINKED ISSUE #5164: Phoenix generator generates inadequate check for IPV6 Ecto flag
### Environment

* Elixir version (elixir -v):
  ```
  $ elixir -v
  Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
  
  Elixir 1.14.2 (compiled with Erlang/OTP 25)
  ```
* Phoenix version (mix deps): 1.7.0-rc.0

* Operating system: Ubuntu 22.04

### Expected behavior

I want to create a Dockerfile that will allow me to choose IP6 support or not. IP6 is required on Fly.io, but is not required when I'm testing the Docker image locally on my dev machine. 

The `flyctl` CLI adds the following lines to `Dockerfile`:

```docker
# Appended by flyctl
ENV ECTO_IPV6 true
ENV ERL_AFLAGS "-proto_dist inet6_tcp"
```

I have changed this to:

```docker
ARG IPV6
....
# only set IP6 env var values in the image if $IPV6 ARG is truthy
ENV ECTO_IPV6=${IPV6:+true}
ENV ERL_AFLAGS=${IPV6:+"-proto_dist inet6_tcp"}
```

Setting environment var `$IPV6` to a falsey value should then deter Ecto from using `:inet6`.

### Actual behavior

Even with my environment containing `IPV6=0`, my Phoenix app starts up in `:inet6` mode.

### Analysis

The Docker construct `ENV ECTO_IPV6=${IPV6:+true}` when `$IPV6` is falsey is equivalent to:

```
ENV ECTO_IPV6=
```

So the `$ECTO_IPV6` variable is present in the environment that Phoenix starts with, but it has no value. However, the check that the generator creates in `config/runtime.exs` is:

```elixir
  maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []
```

So `maybe_ipv6` will contain `[:inet6]` if the environment contains the key `ECTO_IPV6`, **irrespective** of any value it has.

### Proposed solution

In my local `config/runtime.exs`, I have changed this line to:

```elixir
  maybe_ipv6 = if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []
```

The Phoenix generator could consider adopting a similar pattern? Or a more permissive approach, perhaps less of a potentially breaking change from the current behaviour, would be check that `$ECTO_IPV6` is not either empty or equal to `"0"`

### PR DESCRIPTION
**Pull request by simonedavico**
This PR implements the backward compatible approach suggested by @ijdickinson in [this comment](https://github.com/phoenixframework/phoenix/issues/5164#issuecomment-1399218037).

We enable ipv6 when `ECTO_IPV6` is not empty, or `0`, or `false`.

Fixes #5164.

Built with ❤️ in Milan during [Open Source Saturday](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/)

### CODE REVIEW

**Comment by ijdickinson** [comment]
Thanks for doing this, @simonedavico. I was hoping to get to it in a week or so ... I've just been really busy at work!

**Comment by simonedavico** [comment]
> Thanks for doing this, @simonedavico. I was hoping to get to it in a week or so ... I've just been really busy at work!

@ijdickinson my pleasure! Had some free time on my hands 😄

File: installer/lib/phx_new/generator.ex [hunk 1]
```diff
@@ -356,7 +356,8 @@ defmodule Phx.New.Generator do
           For example: ecto://USER:PASS@HOST/DATABASE
           \"""
 
-      maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []
+      maybe_ipv6 = if System.get_env("ECTO_IPV6") not in ["", "0", "false"], do: [:inet6], else: []
```
Comment (josevalim) [inline installer/lib/phx_new/generator.ex:359]:
```suggestion
      maybe_ipv6 = if System.get_env("ECTO_IPV6") in ["true", "1"], do: [:inet6], else: []
```

File: lib/mix/tasks/phx.gen.release.ex [hunk 2]
```diff
@@ -113,7 +113,7 @@ defmodule Mix.Tasks.Phx.Gen.Release do
 
       Add the following to your config/runtime.exs:
 
-          maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []
+          maybe_ipv6 = if System.get_env("ECTO_IPV6") not in ["", "0", "false"], do: [:inet6], else: []
```
Comment (josevalim) [inline lib/mix/tasks/phx.gen.release.ex:116]:
```suggestion
          maybe_ipv6 = if System.get_env("ECTO_IPV6") in ["true", "1"], do: [:inet6], else: []
```

File: installer/test/phx_new_test.exs [hunk 3]
```diff
@@ -178,7 +178,10 @@ defmodule Mix.Tasks.Phx.NewTest do
 
       assert_file("phx_blog/config/runtime.exs", fn file ->
         assert file =~ config
-        assert file =~ ~S|maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []|
+
+        assert file =~
+                 ~S|maybe_ipv6 = if System.get_env("ECTO_IPV6") not in ["", "0", "false"], do: [:inet6], else: []|
```
Comment (josevalim) [inline installer/test/phx_new_test.exs:183]:
```suggestion
                 ~S|maybe_ipv6 = if System.get_env("ECTO_IPV6") in ["true", "1"], do: [:inet6], else: []|
```

File: installer/lib/phx_new/generator.ex [hunk 4]
```diff
@@ -356,7 +356,8 @@ defmodule Phx.New.Generator do
           For example: ecto://USER:PASS@HOST/DATABASE
           \"""
 
-      maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []
+      maybe_ipv6 = if System.get_env("ECTO_IPV6") in ["true", "1"], do: [:inet6], else: []
```
Comment (josevalim) [inline installer/lib/phx_new/generator.ex:359]:
```suggestion
      maybe_ipv6 = if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []
```

File: installer/test/phx_new_test.exs [hunk 5]
```diff
@@ -178,7 +178,10 @@ defmodule Mix.Tasks.Phx.NewTest do
 
       assert_file("phx_blog/config/runtime.exs", fn file ->
         assert file =~ config
-        assert file =~ ~S|maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []|
+
+        assert file =~
+                 ~S|maybe_ipv6 = if System.get_env("ECTO_IPV6") in ["true", "1"], do: [:inet6], else: []|
```
Comment (josevalim) [inline installer/test/phx_new_test.exs:183]:
```suggestion
                 ~S|maybe_ipv6 = if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []|
```

**Comment by simonedavico** [comment]
Hey @josevalim, in the issue discussion @ijdickinson proposed keeping the behaviour backward compatible. I guess this vuol mean enabling IPV6 also when `ECTO_IPV6` is equal to empty string, correct?

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

File: installer/lib/phx_new/generator.ex [hunk 6]
```diff
@@ -356,7 +356,8 @@ defmodule Phx.New.Generator do
           For example: ecto://USER:PASS@HOST/DATABASE
           \"""
 
-      maybe_ipv6 = if System.get_env("ECTO_IPV6"), do: [:inet6], else: []
+      maybe_ipv6 = if System.get_env("ECTO_IPV6") in ~w(true 1), do: [:inet6], else: []
```
[the remark this answers is not in the document]
Comment (josevalim) [reply installer/lib/phx_new/generator.ex:359]: What we write doesn't matter here for old apps because it will only affect new apps anyway.
