### PR TITLE
fix(Mix.Phoenix): validate attrs on generators

### LINKED ISSUE #1215: Invalid mix phoenix.gen.json generates code that causes exception once command is fixed
Sorry, if this is my ignorance again and also for opening such minor bugs, but it would be nice if the command that has an error in it failed completely and didn't generate code that needs to be cleaned up: 

```console
$mix phoenix.new game
$cd game
$mix phoenix.gen.json Player players name:string position:integer info:jsonb
* creating web/controllers/player_controller.ex
* creating web/views/player_view.ex
* creating test/controllers/player_controller_test.exs
* creating web/views/changeset_view.ex
** (Mix) Unknown type `jsonb` given to generator
$
$ mix phoenix.gen.json Player players name:string position:integer
Compiled web/views/changeset_view.ex
Compiled web/views/player_view.ex

== Compilation error on file web/controllers/player_controller.ex ==
** (CompileError) web/controllers/player_controller.ex:14: Game.Player.__struct__/0 is undefined, cannot expand struct Game.Player
    (elixir) src/elixir_map.erl:55: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_clauses.erl:36: :elixir_clauses.clause/7
    (elixir) src/elixir_def.erl:178: :elixir_def.translate_clause/7
    (elixir) src/elixir_def.erl:167: :elixir_def.translate_definition/8
    (elixir) src/elixir_def.erl:82: :elixir_def.store_definition/9
    web/controllers/player_controller.ex:13: (module)
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

I can get around this by deleting game dir (or possibly running some mix cleanup commands), but to me invalid command should be validated upfront and fail fast?

### PR DESCRIPTION
**Pull request by Gazler**
This prevents code from being generated if one of the types is invalid.

Fixes #1215

### CODE REVIEW

File: lib/mix/phoenix.ex [hunk 1]
```diff
@@ -88,12 +91,13 @@ defmodule Mix.Phoenix do
...
   def attrs(attrs) do
-    Enum.map attrs, fn attr ->
+    attrs
+    |> Enum.map fn attr ->
       case String.split(attr, ":", parts: 3) do
         [key, comp, value] -> {String.to_atom(key), {String.to_atom(comp), String.to_atom(value)}}
         [key, value]       -> {String.to_atom(key), String.to_atom(value)}
         [key]              -> {String.to_atom(key), :string}
-      end
+      end |> validate_attr
```
Comment (chrismccord) [inline lib/mix/phoenix.ex]: Lets rework this pipeline with parens. Enum.map should have parens and the piping precedence should be obvious

**Comment by chrismccord** [comment]
This looks great! I have just one small comment then ready to go

**Comment by chrismccord** [comment]
<3 <3 <3
