### PR TITLE
Checks force_ssl has not changed from compile time to runtime

### LINKED ISSUE #3586: `force_ssl` doesn't work in releases.exs
We're trying to enforce ssl and following the [docs](https://hexdocs.pm/phoenix/endpoint.html#force-ssl), we added the `force_ssl` config, but we are also using elixir releases, so we (arbitrarily) put it in our releases.exs file instead of our prod.exs file and it is silently ignored.

I think this happens because `Plug.SSL` is injected by a macro seen [here](https://github.com/phoenixframework/phoenix/blob/029098e38ca830c35e832b44e58a0cd641fe24f1/lib/phoenix/endpoint.ex#L453). Since releases.exs is for runtime configs, the `force_ssl` configuration isn't present during build time when the macros are evaluated and `Plug.SSL` is never injected.

I'm not sure if "fixing" this is the right way to go or if we should just update the documentation to mention that the config must not be in a runtime config such as releases.exs. 

I'm happy to help make the change if you let me know how you'd like to proceed. Thanks again for a great library!

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.4.10

### PR DESCRIPTION
**Pull request by jesseshieh**
Resolves #3586

### CODE REVIEW

**Comment by jesseshieh** [comment]
@josevalim no rush, but just letting you know this is here whenever you get a chance. Happy to make changes, just lemme know.

File: lib/phoenix/endpoint/supervisor.ex [hunk 1]
```diff
@@ -11,17 +11,47 @@ defmodule Phoenix.Endpoint.Supervisor do
...
       {:error, _} = error ->
         error
     end
   end
 
+  defp check_force_ssl(otp_app, mod) do
+    compile_config = mod.__compile_config__() |> Keyword.get(:force_ssl)
+
+    runtime_config =
+      config(otp_app, mod)
```
Comment (josevalim) [inline lib/phoenix/endpoint/supervisor.ex]: I don't think we should build the config list again, as we already do on init. My suggestion is to move this logic to inside the `init` function.

File: lib/phoenix/endpoint/supervisor.ex [hunk 2]
```diff
@@ -11,17 +11,47 @@ defmodule Phoenix.Endpoint.Supervisor do
...
+      log_access_info(otp_app, mod)
+      ok
+    else
       {:error, _} = error ->
         error
     end
   end
 
+  defp check_force_ssl(otp_app, mod) do
+    compile_config = mod.__compile_config__() |> Keyword.get(:force_ssl)
```
Comment (josevalim) [inline lib/phoenix/endpoint/supervisor.ex]: Instead of validating only `force_ssl`, we can simply validate all keys in `compile_config`. That was the goal with making it generic. In a nutshell, you can traverse this keyword list, comparing it with the values in runtime_config.

File: lib/phoenix/endpoint/supervisor.ex [hunk 3]
```diff
@@ -433,4 +463,8 @@ defmodule Phoenix.Endpoint.Supervisor do
       Logger.info("Access #{inspect(endpoint)} at #{endpoint.url()}")
     end
   end
+
```
Comment (josevalim) [inline lib/phoenix/endpoint/supervisor.ex]: Please add a tiny documentation sayings its purpose.

**Comment by josevalim** [comment]
@jesseshieh glad you pinged me as I don't receive notifications. :) It looks really good, just some ccomments and we should be good to go!

File: lib/phoenix/endpoint/supervisor.ex (hunk 1 above)
Comment (jesseshieh) [reply lib/phoenix/endpoint/supervisor.ex]: Oh good catch. Moved.

File: lib/phoenix/endpoint/supervisor.ex (hunk 2 above)
Comment (jesseshieh) [reply lib/phoenix/endpoint/supervisor.ex]: Oh I see, sorry about that. I wasn't sure if the error message would be generic enough for future keys, but I think it should be alright. Updated.

File: lib/phoenix/endpoint/supervisor.ex (hunk 3 above)
Comment (jesseshieh) [reply lib/phoenix/endpoint/supervisor.ex]: Added.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
