### PR TITLE
Look up system variable when checking origin

### LINKED ISSUE #1947: Check_origin fails when endpoint is configured with environment variable
I have configured my endpoint with an environment variable.

    config :app, App.Endpoint, 
      ...
      url: [
        host: {:system, "HOST"},
      ],
      ...

When I try to connect to my socket, it fails with `Could not check origin for Phoenix.Socket transport.`

### Environment

* Elixir version (elixir -v): 1.3.2
* Phoenix version (mix deps): 1.2.1
* NodeJS version (node -v): 6.6.0
* NPM version (npm -v): 3.10.3
* Operating system: Debian Linux

### Expected behavior

The origin check passes, when started with the correct HOST variable.

### Actual behavior

The origin check fails.

### PR DESCRIPTION
**Pull request by ThijsWouters**
Fixes #1947

### CODE REVIEW

**Comment by josevalim** [comment]
@ThijsWouters great job. I just left one tiny comment for us to improve the tests.

File: test/phoenix/transports/transport_test.exs [hunk 1]
```diff
@@ -21,6 +25,7 @@ defmodule Phoenix.Transports.TransportTest do
 
   setup do
     Logger.disable(self())
+    on_exit fn -> Endpoint.config_change([{Endpoint, @config}], []) end
```
Comment (ThijsWouters) [inline test/phoenix/transports/transport_test.exs]: Well, I found another bug when I did it like this.

In `force_ssl/4` there is also a lookup to the host of the url.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
